---
title: "Course Assignment - Desctription"
output: html_document
---

This markdown explains the steps involved in analysing the data and putting together the end resutl, a tidy file.

The original data contain two set of three files each. The files are saved in working directory. Each set has following files
Set 1 (Test)
* x_test, the file containing raw data for 30 subjects on 6 activities;
* y_test, the file containing the names 6 activities
* subject_test, a file containing vector of subject identifiers correspnding to the measurements in first file.

Set 2 (Train) - This has the same structure as explained above for test files
- x_train, the file containing raw data for 30 subjects on 6 activities;
- y_train, the file containing the names 6 activities
- subject_train, a file containing vector of subject identifiers correspnding to the measurements in first file.



You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
